### ISSUE TITLE
Implement resource to configure user entitlements for AAD and GitHub backed users

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As a developer, I want the ability to entitle a member to an AzDO organization. This will allow me to add them to groups AzDO groups so that they have permissions to interact with the AzDO org/projects that I've provisioned.

### New or Affected Resource(s)
* `azuredevops_user_entitlement`

### Potential Terraform Configuration
```hcl
// outputs: id, descriptor
resource "azuredevops_user_entitlement" "user" {
    // ex AAD: foobar@microsoft.com
    // ex GH: foobar
    // note: a change here forces a delete/create - update not supported
    principal_name = string, optional

    // ex AAD: e97b0e7f-0a61-41ad-860c-748ec5fcb20b
    // ex GH: 2497673
    origin_id = string, optional

    // values: "aad" (default), "ghb"
    // note: a change here forces a delete/create - update not supported
    origin = string, optional
}
```

### Acceptance Criteria
- [ ] Support `CREATE`, `READ`, `DELETE` operations for this resource.
- The following business logic surrounding the parameters should be implemented:
  - [ ] If `origin_id` is provided, it will be used. If `principal_name` is also supplied, an error will be reported
  - [ ] if `origin_id` is "" and `principal_name` is supplied, the `principal_name` will be used
  - [ ] if `origin_id` is `""` and `principal_name` is `""`, an error will be reported

- [ ] Support `CREATE`, `READ`, `DELETE` operations for this resource.
- [ ] Unit tests written and pass as part of CI
- [ ] Acceptance tests written and pass as part of CI

### References
 * Design: https://github.com/microsoft/terraform-provider-azuredevops/issues/74

**Comment by tmeckel** [comment]
@nmiodice what is missing here from my point of view, is the fact how to specify the actual entitlement. Entitlements are integer values (bit field) of permissions defined by the security namespace respectively. What permissions (entitlements) a security namespace defines and what bit has to be set or cleared for a specific entitlement can be read from the securitynamespace REST API endpoint. 

Because the permission/entitlement model of DevOps/TFS is so flexible I think we should decide if we put the burden on the user to create the entitlement bitfield values using the bit manipulation functions of Terraform in conjunction with the securitynamespace REST API endpoint (which would indeed would mean that we must provide a data sources for this!). Or if we persue a more easy to use path like I described in #103 in which I put the available entitlements for a project group into the resources schema. As said this would be much easier to use but would require us to adapt any changes to the corresponding security namespace.

## References

* [Security Namespaces - Query](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/security%20namespaces/query?view=azure-devops-rest-5.1)

* [QuerySecurityNamespaces(context.Context, QuerySecurityNamespacesArgs) (*[]SecurityNamespaceDescription, error)](https://github.com/microsoft/azure-devops-go-api/blob/273e55a7119a766faedd7a951bc1894171f89bd9/azuredevops/security/client.go#L30)

* [type SecurityNamespaceDescription struct](https://github.com/microsoft/azure-devops-go-api/blob/273e55a7119a766faedd7a951bc1894171f89bd9/azuredevops/security/models.go#L87)

* [type ActionDefinition struct](https://github.com/microsoft/azure-devops-go-api/blob/273e55a7119a766faedd7a951bc1894171f89bd9/azuredevops/security/models.go#L55)
