### ISSUE TITLE
Implement resource for AzDO group membership

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As a developer, I want the ability to add and remove a user from an AzDO group. Furthermore, I want this to be generically implemented using entity `descriptors` so that the resource can be used for things other than users/groups.

### New or Affected Resource(s)
* `azuredevops_group_membership`

### Potential Terraform Configuration
```hcl
// outputs: n/a
resource "azuredevops_group_membership" "membership" {
    // ex azuredevops_group.group.descriptor
    // note: a change here forces a delete/create - update not supported
    group = string, required

    // ex [azuredevops_member_entitlement.member.descriptor]
    // note: must have at least 1 element; changes trigger update
    subjects = list[string], required
}
```

### Acceptance Criteria

- [x] Support `CREATE`, `READ`, `DELETE`, `UPDATE` operations for this resource.
- [x] The "group" will be represented by a `descriptor`
- [x] The "subjects" being added to the group will be represented by a `descriptor`
- [x] Unit tests written and pass as part of CI
- [x] Acceptance tests written and pass as part of CI

### References
 * Design: https://github.com/microsoft/terraform-provider-azuredevops/issues/74

**Comment by nmiodice** [comment]
There is a nearly complete implementation on this branch: https://github.com/microsoft/terraform-provider-azuredevops/tree/niiodice/graph-membership

It is missing all tests, and needs to be re-based off master as it is quite old at this point

**Comment by tmeckel** [comment]
@nmiodice I'd propose a different syntax for the resource. It provides the possibility to manage the memberships of a group using a list of principals.  

```hcl

data "azuredevops_group" "lookup-group" {
   principalname_name  = "[Cloud-Operations]\\Readers"
}

data "azuredevops_user" "lookup-user-1" {
   principalname_name  = "TestUser1@contoso.com"
}

data "azuredevops_user" "lookup-user-2" {
   principalname_name  = "TestUser2@contoso.com"
}

resource "azuredevops_group_membership" "membership" {
    // ex azuredevops_group.group.descriptor
    // note: a change here forces a delete/create - update not supported
    group_id =  data.azuredevops_group.lookup-group.id

    // ex azuredevops_member_entitlement.member.descriptor
    // note: a change here forces a delete/create - update not supported
    principals = [
         data.azuredevops_group.lookup-user-1.id,
         data.azuredevops_group.lookup-user-2.id
    ]
}
```

**Comment by nmiodice** [comment]
@tmeckel, I was thinking of that approach as well but was concerned that having a list means that the resource implementation becomes more complicated due to the fact that you need to consider how to handle changes to the list, which means supporting update. With the current approach, that logic is managed by the Terraform core.

A similar approach for configuring lists like this is supported by Terraform itself, though in a slightly more verbose form:

```hcl
data "azuredevops_group" "a" {
  project_id = "..."
  name       = "..."
}

data "azuredevops_group" "b" {
  project_id = "..."
  name       = "..."
}

data "azuredevops_group" "c" {
  project_id = "..."
  name       = "..."
}

locals {
    group_members = [data.azuredevops_group.b.id, data.azuredevops_group.c.id]
}

resource "azuredevops_graph_membership" "membership" {
  count = length(local.group_members)
  container_descriptor = data.azuredevops_group.a.id
  subject_descriptor   = local.group_members[count.index]
}
```

**Comment by tmeckel** [comment]
@nmiodice I can definitely reproduce the argument, having the Terraform handling the update process for a resource. But from my point of view I think you must find a way to balance the effort you've to put into an implementation and it's ease of use. 

With your approach you force the user to implement (use) a count (for_each) strategy in favor of having an easy (simple) implementation.  I'd favor the ease of use for a resource because the more of code you've to use to implement a specific function, the more error prone it is. In addition Terraform HCL is a great configuration but definitely NOT a programming language.

Personally I'm not happy that Hashicorp is thriving to create a programming language out of HCL, but if I'd need a real programming language to deploy my Cloud resources I'd always opt in for [Pulumi](https://www.pulumi.com/) and not for Terraform!

Copying @tiwood for reference

**Comment by nmiodice** [comment]
Hmm... I think you have convinced me :) I'll go ahead and update the acceptance criteria. Also i will make the property names more user friendly.

**Comment by tmeckel** [comment]
@nmiodice I really hope with a joint effort we can create an awesome Terraform provider for Azure DevOps! ☺️

**Comment by nmiodice** [comment]
Community feedback like yours is critical to making sure that we are building the right thing that people will *actually use.*

Please keep the feedback coming!!

**Comment by tmeckel** [comment]
You're really welcome! But @tiwood would definitely warn you about me 😆 

But getting serious again here: while I was writing my issues and looking what you and @KeithJRome are doing, perhaps we should have some sort of a "test driven" approach in which we challenge each others HCL code proposals for the different data sources and resources by trying to write down some HCL code for oneselve and see "how it feels" to use the proposed new functionality and how it fits to the existing components. Just an idea though :relaxed:

**Comment by tmeckel** [comment]
Oh and another thing: we should be consistent about the names of the properties of the resources and data sources. Your're using `subjects` for the ´references to the identities that should be a member of a group. Whereas I proposed the `principals`block in #153 or #104. I definitely insist on my proposal here, but we should agree on a common name, so that the Terraform resources are easy and more important can be used in a **predictable** way.

**Comment by nmiodice** [comment]
+1 on your last comment -- I've been driving my terminology primarily based on the concepts that exist in the [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/add?view=azure-devops-rest-5.1). This is not to say that this is the **right** way, though, but it typically been the place that I start.

I see opportunity to distill the complicated API spec into something more user-friendly. We can do this in two ways
 - Use the same terminology across resources/data sources
 - Use a context-specific term. I.e., perhaps `members` for `group_membership`, and something more context specific for permissions

Thoughts? 

In every case, the "things" that we are dealing with are really `descriptors`, but I fear that the

**Comment by tmeckel** [comment]
Me and @tiwood had an intense discussion yesterday about the HCL code for the `azuredevops_git_permissions` #153 or the `azuredevops_project_permissions` #104 resources, because we (all) must find a way to have the complicated and matured DevOps (TFS) API converted into a concise and easy to use Terraform Resource Provider and in the end @tiwood convinced me to have two different properties for a user (or group) principal. At first the `id` which is **always** required for a Terraform resource and an additional one `id_descriptor` which yields the converted subject type which can be directly used inside an ACE in a security namespace to assign an entitlement. 

With this approach the API will throw an error if it can't match the principal and on the other hand you can consistently state in the documentation that **at every occasion** when you're fiddling with permissions you must use the `id_descriptor` property. 

Even better: the burden to convert the `descriptor` of a principal returned from the `graph` API to a `security namespace` ACE principal is put on the Terraform resource which encapsulates the REST API object (user, group, service principal etc.).

I think in the end you'll never can hide the odd edges of a matured API behind a new API. Some ugly facts will always shine through. Or you really take the challenge and write a complete new wrapper around the old API. What will make not much sense to me, because the effort you've to put in that new API outweighs the benefits you gain. 

Apropos documentation: how we gonna generate the documentation for the DevOps Terraform provider? The guys at the [Office 365 CLI project](https://pnp.github.io/office365-cli/) project are using [MKDocs](https://www.mkdocs.org/) for it.
