### ISSUE TITLE
Add tools go for tool dependency management

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/terraform-provider-azuredevops#155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Adding tools.go is the best practice to manage the dependency of the go tools. 
Not tested, however, sometimes we have an issue related version of the go tools (e.g. linting) 
It might be important to use the same version for the tools both on development environment and CI. 

### New or Affected Resource(s)

NA

### Potential Terraform Configuration

Add tools.go and add tools that related this project. 

```go
// +build tools

package tools

import (
	_ "golang.org/x/tools/cmd/stringer"
)
```

### References

https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by nmiodice** [comment]
@TsuyoshiUshio can you help me understand which tools should be included in `tools.go` with this suggestion?

here is a list of tools that I think we use -- perhaps you can help me fill in the table so that we can make the acceptance criteria for this task more concrete:

| tool name | used for | version controlled by | should be in `tools.go`? |
| --- | --- | --- | --- |
| bash | script execution | os package manager | no |
| go, gofmt | build, test, format checks | user via [install steps](https://golang.org/doc/install)  | no |
|  mockgen | mock generation | `./scripts/generate-mocks.sh` calls `go get github.com/golang/mock/mockgen` | yes |

Are there any other dependencies that you know of that should be in `tools.go`?

**Comment by TsuyoshiUshio** [comment]
It looks good. The scenario covers something that in under the $GOPATH/bin and not under control of Go Modules. This is my $GOPATH/bin. Currently, you don't use it however, if you use golint on CI, You might want to make these under the control go Go Modules, In this case, you can configure `tools.go` 

```
dlv          go-outline   gocode       godef        goimports    gomodifytags goplay       gotests      impl
fillstruct   go-symbols   gocode-gomod godoctor     golint       gopkgs       gorename     guru
```

**Comment by nmiodice** [comment]
This should be solved via the `vendor` directory now. The contents of this directory are asserted to be accurate via `make check-vendor-vs-mod` on each PR as well.
