### ISSUE TITLE
Add KeyVault reference feature for VariableGroups Resource

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/terraform-provider-azuredevops#172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer, I want the ability to link KeyVault to the Variable Groups. 

### Dependency

* https://github.com/microsoft/terraform-provider-azuredevops/issues/170
* Service Connection with Service Principal. Story is not coming yet. Watch out this issue. https://github.com/microsoft/terraform-provider-azuredevops/issues/3

### New or Affected Resource(s)

* `azuredevops_variable_group`

### Potential Terraform Configuration

```hcl
resource "azuredevops_service_endpoint" "sp_service_endpoint" { 
     :  
}

resource "azuredevops_variable_group" "my_variable_group" {
      project_id = azuredevops_project.id    // Required
      keyvault = {
        name = "avault"
        service_endpoint_id = azuredevops_service_endpoint.sp_service_endpoint.id
      }
      name = "my-variable-group"  
      description = "my variable group description"
      allow_access  = "true"
      variables {
            key  = "key1"
            value = "value1"
            is_secret = true
      }
      variables {
             key = "key2"
             is_secret = true
             is_vault = true
     }
}
```

### Acceptance criteria 

- [ ] Support `Create`, `Read`, `DELETE`, `UPDATE` operation for KeyVault reference
- [ ] Unit tests written and pass as part of CI
- [ ] Acceptance tests written and pass as part of CI
- [ ] User Document is written. You can find it [here](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/index.md)

### References

* Design: https://github.com/microsoft/terraform-provider-azuredevops/issues/21

**Comment by nmiodice** [comment]
Note: blocked on https://github.com/microsoft/terraform-provider-azuredevops/issues/171

**Comment by mikaelkrief** [comment]
@nmiodice , I am interested to work on this . can you assign to me

**Comment by nmiodice** [comment]
@mikaelkrief  done!

**Comment by mikaelkrief** [comment]
@nmiodice , Can you add requirement for this task, it's to create Azure RM service connection,, see the issue #161.

I can work on the #161 before this issue.

**Comment by LaurentLesle** [comment]
I use a lot variable groups to keyvault keys as a way to securely expose them to Azure Devops pipelines. It also allow security teams to inject their secrets while keeping them hidden from the devops team. I can see the the blocker #170 and #161 have been completed. Is that something that can be prioritized?

**Comment by EliiseS** [comment]
@nmiodice and I have discovered a blocking issue in the go SDK implementation, found here: https://github.com/microsoft/azure-devops-go-api/issues/58

**Comment by EliiseS** [comment]
Here's are the discoveries I've made while researching this issue:

**POST** `https://<azdo>.visualstudio.com/_apis/distributedtask/variablegroups`
``` json
{
    "description": "",
    "name": "KeyVault Link",
    "providerData": {
        "serviceEndpointId": "ed6a8047-922b-4378-b74b-50087580757c",
        "vault": "tsushivault",
        "lastRefreshedOn": "2019-10-30T08:37:16.484Z"
    },
    "type": "AzureKeyVault",
    "variables": {
        "hello": {
            "isSecret": true,
            "value": "",
            "enabled": true,
            "contentType": "",
            "expires": null
        }
    },
    "variableGroupProjectReferences": [
        {
            "description": "",
            "name": "KeyVault Link",
            "projectReference": {
                "id": "<PROJECT_ID>",
                "name": ""
            }
        }
    ]
}
```
- This API does not have validation on what the parameters can be set to. I've been able to set these parameters to various incorrect values: `key`, `value`, `enabled`, `expires`, `content_type`, `serviceEndpointId`, `vault`. 
- This API endpoint is used to update the variable group parameters in the UI
- In order to successfully use the keyvault keys in the pipeline only `serviceEndpointId`, `vault` and `key` need to be set to the correct values. I've successfully used a parameter in the pipeline that was set `enabled: false` in the variable group (enabled in the key vault however).

![image](https://user-images.githubusercontent.com/12761692/80597185-661cbc80-8a1f-11ea-8b74-8389a76ddd05.png)

**GET** `https://dev.azure.com/eliise/<project>/_apis/distributedtask/serviceendpointproxy?endpointId=<end_point_id>&api-version=5.0-preview.2`

![image](https://user-images.githubusercontent.com/12761692/80598359-2060f380-8a21-11ea-83e8-9d6e411e7dc3.png)

- Used in the VariableGroup UI to retrieve what the values should be according to the key vault
- This update is only triggered in the VariableGroup UI. When creating the key vault variable group via the API it'll forever return it the values you set (or didn't set) them do, never representing the reality of what's they are set to in the key vault (for example, if the key is set to expires in the key vault)
- Endpoint returns incorrectly formatted json in it's message body

**Comment by tmeckel** [comment]
@EliiseS I see you used Postman for your analysis. I'd prefer to use the officially maintained Python API which allows me to switch between API Versions 5.1 and 6.0.  In addition `api-version=5.0-preview.2` is pretty outdated. Perhaps `api-version=5.1` (the official one) is worth a try.  

To my own shame, I have to say that I personally have fallen for the problems with the different API versions so often that I now abstain from using Postman because I often forget to set the query parameter 'api-version' correctly, although of course you can also define it using a global variable.

The bad thing about the Azure DevOps API is the fact that for many REST endpoints it also returns an answer if you do not specify an `api-version` at all. And the returned data is often very different from the one you expect or know from earlier analysis.
