### ISSUE TITLE
Install AZDO in devops pipelines

### ISSUE THREAD

**Issue by SidGrundfos** [microsoft/terraform-provider-azuredevops#224]
Hi Team, I am trying to create a devops service connection to ACR via azuredevops profider terraform.
How do I install the provider in my release pipeline?

**Comment by nmiodice** [comment]
Unfortunately since this is not yet hosted anywhere official (yet) you won't be able to include this provider using a `provider` block in Terraform HCL.

You will need to [build](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/scripts/build.sh) and [install](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/scripts/local-install.sh) this plugin locally on the build agent. It can be done as part of a pipeline, or once if you are self-hosting the build agent.

We are working with Hashicorp to see if we can get this hosted on their terraform registry so you don't have to do this!

Happy to help further if needed.

**Comment by jasonsears** [comment]
Any thoughts on timing for this being in the Terraform Registry? We are fairly new to Terraform and using their Terraform Cloud. It appears providers must be in the registry to be utilized from TF Cloud. I've opened a support case with Terraform to confirm my suspicion regarding community providers and TF Cloud.

**Comment by SidGrundfos** [comment]
Any updates on the availability of the binaries in Terraform Registry

**Comment by nmiodice** [comment]
Not yet -- we are working towards this as a goal, but it involves cross company collaboration. Nothing yet to report on this, I'll keep you in the loop.

For now, you can use the scripts located in `scripts/` to build the binary and install it locally. Perhaps it is possible to include it, pre-built, in your repository? 

More info here: https://www.terraform.io/docs/plugins/basics.html#installing-plugins

**Comment by nmiodice** [comment]
I'm closing this in favor of the official tracking issue here - https://github.com/microsoft/terraform-provider-azuredevops/issues/241
