### ISSUE TITLE
Identify & document strategy to implement more broad / general service connection resource

### ISSUE THREAD

**Issue by nmiodice** [microsoft/terraform-provider-azuredevops#3]
Currently the only supported service connection is a GitHub service connection. This resource should be extended to support all possible service connections. This will also require refactoring to support optional parameters per type of service connection (e.g., github_service_endpoint_pat).

* Copied from https://github.com/nmiodice/terraform-azure-devops-hack/issues/40

# Acceptance Criteria
 - [ ] Document resource schema
 - [ ] Document validation rules for how to validate configurations 
 - [ ] How will we decide what changes can be updated vs require a delete/create to occur?
 - [ ] What lives in the state?

The following AC are added based on retrospective feedback:
 - [ ] Design should live in this issue (the comments) and be reviewed by the core contributor team. It should cover the items above as well as any other design considerations that impact the implementation
 - [ ] Implementation story breakdown into backlog, **after the design review has been completed**

**Comment by ThePhen** [comment]
After reviewing the [relevant ADO Go SDK code](https://github.com/microsoft/azure-devops-go-api/tree/dev/azuredevops/serviceendpoint), I'm inclined to lean towards 1st creating the generic I/F for creating service endpoints.

So there would be a generic resource for this, before there would be ACR and AzRM specific sub-types.

_Note: the AZ DevOps CLI does provide convenience operations for some sub-types._

**Comment by nmiodice** [comment]
@ThePhen I know you are still deep diving, but I'm interested in whether you think that there should be a single `service_endpoint` resource, or a different resource for each type of service endpoint?

Of course the order in which we implement can be decided later, but I'm curious which direction you are leaning (once you have an opinion, that is). I think you answered it in your last comment but it was not clear to me which direction you were leaning.

**Comment by ThePhen** [comment]
@nmiodice I've tried teasing out a little code, tonight, to get a feel for one choice or the other. 

When I wrote the comment, earlier, I had been looking at the available structures with the ADO Go SDK, and also looking at some CLI code that accomplished creating a new ACR Service End Point.

Since then, I've realized that its very simple to create a type-specific resource for each of the types that's most useful (vs. creating something that would re-export the ADO Go SDK). I don't think this remains 'true' to the API we're putting a TF Provider 'adapter' over, but it makes using the provider a lot simple, for the most interesting use cases we've been talking about.

So, I think it's less pure, but faster to go with a set of service endpoint types, vs. a single resource.

**Comment by ThePhen** [comment]
# Investigation into Service Endpoint Creation

My goal has been to dtermine which data are needed in order to CRUD Azure Devops Service Endpoint resources (aka 'Service Connections').

Initially, we're most interested in being able to manage the following service endpoint types:
* GitHub
* Azure RM
* ACR (via the Docker Registry type)

## Approach

1. Created one of the types via the AzDO web UI.
2. Using a combination of Chrome Dev Tools and the Azure Dev Ops CLI, figure out which data are used to CRUD the service endpoint.
3. Use the CLI `az devops service-endpoint create` command with a JSON file (the service endpoint configuration) to create another service endpoint of the same type.
4. Use the web UI to test that the newly managed endpoint is nominally working.
5. Remove/edit the JSON configuration to help determine which data are not actually required for CRUD.
6. Repeat, from step #3 onwards, to experiment.

## Findings

Here are the required data for each of the service endpoint types, as derrived from the approch.

I've employed the convention of TITLE-CASED-HYPHENATED to indicate where values need to be provided. Otherwise, the values are constant (i.e. the string value should be used exactly as it appears).

### GitHub

```json
{
  "administratorsGroup": null,
  "authorization": {
    "parameters": {
      "accessToken": "GITHUB-PAT"
    },
    "scheme": "PersonalAccessToken"
  },
  "name": "CONNECTION-NAME",
  "owner": "Library",
  "type": "github",
  "url": "http://github.com"
}
```

### Azure RM

```json
{
  "authorization": {
    "parameters": {
      "authenticationType": "spnKey",
      "serviceprincipalid": "SP-ID",
      "serviceprincipalkey": "SP-KEY",
      "tenantid": "TENANT-ID"
    },
    "scheme": "ServicePrincipal"
  },
  "data": {
    "creationMode": "Manual",
    "environment": "AzureCloud",
    "scopeLevel": "Subscription",
    "subscriptionId": "SUBSCRIPTION-ID",
    "subscriptionName": "SUBSCRIPTION-NAME"
  },
  "name": "CONNECTION-NAME",
  "owner": "library",
  "type": "azurerm",
  "url": "https://management.azure.com/"
}
```

### ACR (via the Docker Registry type)

```json
{
  "authorization": {
    "parameters": {
      "loginServer": "LOGIN-SERVER",
      "role": "ROLE",
      "scope": "REGISTRY-ID",
      "servicePrincipalId": "SP-ID",
      "tenantId": "TENENT-ID"
    },
    "scheme": "ServicePrincipal"
  },
  "data": {
    "appObjectId": "",
    "azureSpnPermissions": "",
    "azureSpnRoleAssignmentId": "",
    "registryId": "REGISTRY-ID",
    "registrytype": "ACR",
    "spnObjectId": "",
    "subscriptionId": "SUBSCRIPTION-ID",
    "subscriptionName": "SUBSCRIPTION-NAME"
  },
  "name": "CONNECTION-NAME",
  "owner": "Library",
  "type": "dockerregistry",
  "url": "https://hub.docker.com/"
}
```

## Futher thoughts

After looking at the ACR example, especially, I've come to believve we'll eventually want to pull many of these values from the Azure RM Terraform provider modules, somehow.

To begin with, we can build out our resources in a way the would require the end user to find these vlues 'by-hand'.

**Comment by nmiodice** [comment]
@ThePhen a few questions regarding the resources in general:
 - What is `SP-ID` for the docker registry type? Do we need to provide a service principal? I thought that it was created for us behind the scenes, but I'm not sure.
 - Will we have a `service_endpoint_acr` and `service_endpoint_docker`, or will they share the same resource?
 - It may be worthwhile to note that there are 2 ways (i think) to create ARM connection - one where you specify all the SP details yourself, and one where you just specify a RG and the SP is created for you. Which are we targeting?

Some further questions based on AC:
 - What will the resource schema be for the resources?
 - What kind of validation -- if any -- do we need to verify a "valid" configuration
 - Will we support CREATE/DELETE/READ only, or UPDATE as well? What triggers an UPDATE?

**Comment by ThePhen** [comment]
Issues spun-off from this work-to-date:
#168 #160 #161 #162

**Comment by hbuckle** [comment]
FWIW we started our own provider before we knew about this one and went for a generic service connection resource. Seeing as you can create your own custom ones this seemed to make sense.
https://github.com/clearbank/terraform-provider-azuredevops/blob/development/azuredevops/resource_azuredevops_service_endpoint.go

**Comment by rguthriemsft** [comment]
@hbuckle is correct, there are many extensions that create service connections in AzDo.

**Comment by ThePhen** [comment]
@hbuckle I am in agreement that the provide should export the generic service connection resource from the Go SDK (thus the Az DO REST API). We've been prioritizing 'easy to use' "syntactic sugar" for this first RC of the provider, with the hope that the generic structures would follow.

I fully agree, however, that this provider ought to expose the base REST structures, and then offer convenience that is built on top of that.

**Comment by ThePhen** [comment]
Here’s the example Terraform HCL code that came out of the design work.

```
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_project" "project" {
  project_name       = "Test Project"
  description        = "Test Project Description"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_build_definition" "build_definition" {
  project_id      = azuredevops_project.project.id
  name            = "Test Pipeline"
  agent_pool_name = "Hosted Ubuntu 1604"

  repository {
    repo_type             = "GitHub"
    repo_name             = "nmiodice/terraform-azure-devops-hack"
    branch_name           =. "master"
    yml_path              = "azdo-api-samples/azure-pipeline.yml"
    service_connection_id = azuredevops_serviceendpoint_github.github_serviceendpoint.id
  }
}

resource "azuredevops_serviceendpoint_github" "github_serviceendpoint" {
  project_id      = azuredevops_project.project.id
  connection_name = "GitHub Service Connection"
  github_pat      = "authorization.parameters.accessToken"
}

resource "azuredevops_serviceendpoint_dockerhub" "dockerhub_serviceendpoint" {
  project_id      = azuredevops_project.project.id
  connection_name = "dockerhub test connection"
  docker_username = "authorization.parameters.accessToken"
  docker_password = "secret!"
  docker_email    = "nancy@example.com"
}

resource "azuredevops_serviceendpoint_azurerm" "azurerm_serviceendpoint" {
  project_id        = azuredevops_project.project.id
  connection_name   = "Example Deployment Admin"
  sp_id             = "aaaaaaaa-9999-8888-7777-bbbbbbbbbbbb"
  sp_key            = "bbbbbbbb-3333-4444-5555-cccccccccccc"
  tenant_id         = "cccccccc-7777-4444-aaaa-eeeeeeeeeeee"
  subscription_id   = "dddddddd-2452-4444-9ae2-333333333333"
  subscription_name = "Example Developer"
}

resource "azuredevops_serviceendpoint_acr" "acr_serviceendpoint" {
  project_id        = azuredevops_project.project.id
  connection_name   = "acr connection test"
  login_server      = "examplepp3isolatedserviceacr.azurecr.io"
  sp_role           = "8311e382-0749-4cb8-b61a-304f252e45ec"
  registry_id       = "/subscriptions/dddddddd-2452-4444-9ae2-333333333333/resourceGroups/example-service-app-rg/providers/Microsoft.ContainerRegistry/registries/examplepp3isolatedserviceacr"
  sp_id             = "00000000-8c8e-49ba-9999-4dfdc813c313"
  tenent_id         = "cccccccc-7777-4444-aaaa-eeeeeeeeeeee"
  subscription_id   = "dddddddd-2452-4444-9ae2-333333333333"
  subscription_name = "Example Developer"
}
```

**Comment by iojas** [comment]
Any timeline on `azuredevops_serviceendpoint_acr` ? Thanks.
