### ISSUE TITLE
Add support for managing pool vmss / elastic pools

### ISSUE THREAD

**Issue by Ravio1i** [microsoft/terraform-provider-azuredevops#368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to manage elastic pools in Azure DevOps. This means using terraform to apply and destroy pools linked to Azure VM Scale Sets.

### New or Affected Resource(s)

* `azuredevops_agent_elasticpool`

### Potential Terraform Configuration

```hcl
resource "azuredevops_agent_elasticpool" "pool" {
  name                = "sample-elasticpool"
  auto_provision  = false
  desired_idle      = 1
  max_capacity    = 3
  maxSavedNodeCount = 0
  serviceendpoint_azurem_id = azuredevops_serviceendpoint_azurerm.azure.id
  vmss_id             = "/subscriptions/..../..."
   ....
}
```

### References

* Scale set https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
* API https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools/create?view=azure-devops-rest-6.1

**Comment by aleqsss** [comment]
Hi @Ravio1i,

Please vote on my #204 feature request, since this request seems to be about the same thing. 🙂
Also, there's some additional information inside of it that might be of interest for you.

**Comment by davidaughey** [comment]
I accidentally filed a duplicate on this one.  In it I proposed a change to the existing azuredevops_agent_pool instead of a new resource.

```
resource "azuredevops_agent_pool" "pool" {
  name                   = "scalesetpool"
  description            = "Scale set agent pool"
  pool_type              = "scaleset"
  scaleset_configuration = {
    service_connection_id      = azuredevops_serviceendpoint_azurerm.endpoint.id
    azure_scaleset_name        = "vmss"
    automatically_tear_down    = true
    max_agents                 = 10
    min_agents                 = 2
    delete_excess_agents_delay = 30
  }
}
```

I'm not precious about it and I also like the idea of a new resource.  I'm just adding this into the mix so anyone implementing it has multiple ideas to pull from.  I'm just keen to have the ability to control the VMSS agent pools with Terraform regardless of how it ends up.

**Comment by aristosvo** [comment]
Please vote on this issue: https://developercommunity.visualstudio.com/t/Update-of-the-Go-SDK-to-include-new-feat/10186787

**Comment by dawsonar802** [comment]
Hello, 
Are there any updates on this request?  This is something that would definitely help our need for a client.  Thanks.

**Comment by chrismilson** [comment]
(specifically @xuzhang3 since you set the "blocked" label) Looks like this functionality is available in version 7.0 of the [REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools?view=azure-devops-rest-7.0) and the [go client library](https://github.com/microsoft/azure-devops-go-api/blob/0fc382fb32a151b60fde3340096c1c0c1541325e/azuredevops/v7/elastic/client.go#LL51C131-L51C131). 

I would be happy to try and put together a PR for this.

**Comment by Tolbin400** [comment]
@chrismilson @xuzhang3 do you have any progress on this capability ?

**Comment by xuzhang3** [comment]
@Tolbin400  I have put this to our backlog, basic elastic pool create/update will be supported first

**Comment by Tolbin400** [comment]
> @Tolbin400 I have put this to our backlog, basic elastic pool create/update will be supported first

Any timeline for basic elastic pool support?

**Comment by xuzhang3** [comment]
@Tolbin400   #835  will support manage elastic pools.
