### ISSUE TITLE
cannot add ad group to azure devops group via azuredevops_group_membership Resources

### ISSUE THREAD

**Issue by Ysabo27** [microsoft/terraform-provider-azuredevops#417]
The azuredevops_group_membership Resources cane only add users to azure devops group,
becose ad group dont have principal name

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

terraform 1.0.2
Azure DevOps Provider 0.1.5

### Affected Resource(s)

* `azuredevops_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xuzhang3** [comment]
Hi @huxh27   Can you share your TF script?  Current provider does not support import the AAD group directly.   
Workaround:
1. Create the group(aad) in the organization and use this group as the AAD group
2. Import users in separate emails.

**Comment by a30000931** [comment]
Hi @xuzhang3   - @josh-barker-coles  has an example of how to do that in issue #51 

This successfully links an AAD group to an Azure DevOps team.

We found in tetsing that subsequent removal of the resource removes ALL references to the group in the Org. This seems to be because you can't set both a scope and an origin_id ( based on this comment ) :

[https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group]

scope - (Optional) The scope of the group. A descriptor referencing the scope (collection, project) in which the group should be created. **If omitted, will be created in the scope of the enclosing account or organization.x**

origin_id - (Optional) The OriginID as a reference to a group from an external AD or AAD backed provider. The scope, mail and display_name arguments cannot be used simultaneously with origin_id.

This seems to be an API limitation.
For now we are using a lifecycle block to stop this from causing damage!

**Comment by FISHMANPET** [comment]
@a30000931 I'm new to this provider and terraform in general, can you share what kind of lifecycle block you're using to prevent issues?  None of the [listed options](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) seem like they would help.  `prevent_destroy` seems like a fit at first glance, but since that protection goes away when you remove the configuration, it says terraform will still delete it, leading to the issue you describe.

**Comment by karishma-kohli** [comment]
I am having the same issue - 

Trying to add an Azure AD group to ADO's pre-defined 'Readers' group:

data "azuredevops_group" "readers_group" {
  project_id = azuredevops_project.this.id
  name       = "Readers"
}

resource "azuredevops_group_membership" "assign_readers" {
  group = data.azuredevops_group.readers_group.descriptor
  members = [ "aad_ado_a00z01_read" ]
}

The error:

Error: Error adding group memberships during create: Error adding group memberships during update: Error adding member aad_ado_a00z01_fincrime_synapse_read_cst_prod to group vssgp.Uy0xLTktMTU1MTM3NDI0NS0yOTM4NzU2NjcwLTE2NzIzMzkyNjctMjkyNDcwMzczNS0yMTQzNjM1MjY3LTEtMTAyMDE0MzQzMi0yMjEyNDYyOTEyLTI1MTEyODE2MjMtMzY0Njc3NDg1NQ: Page not found.


How do I get this working?

**Comment by xuzhang3** [comment]
@karishma-kohli  you can add the users with `azuredevops_group`
```hcl
data "azuredevops_group" "aad" {
  name = "<AAD group Name>"
}

resource "azuredevops_group_membership" "assign_readers" {
  group = data.azuredevops_group.readers_group.descriptor
  members = [ data.azuredevops_group.aad.descriptor]
}
```

**Comment by gurretl** [comment]
> lifecycle block

Hi @FISHMANPET 
Indeed, I don't think it will fix the problem. I guess in @a30000931 environment it was just to prevent people to modify groups.
