### ISSUE TITLE
"401 Unauthorized" when creating variable group

### ISSUE THREAD

**Issue by GeromeRen** [microsoft/terraform-provider-azuredevops#64]
Hi guys,

When creating azuredevops variable group using "azuredevops_variable_group", we are experiencing below error. The azuredevops pat we are using has variable groups: Read, Create, & Manage permission. We found when add "Tokens" scope to our pat, there will be no error. May i ask why we need "Tokens" scope in the pat? 

-------------------------------------------------------------
random_string.rs: Creating...
random_string.rs: Creation complete after 0s [id=fP7Mk-y1NU9kp#H9]
azuredevops_variable_group.variablegroup: Creating...

Error: Error creating definitionResourceReference Azure DevOps object: Request returned status: 401 Unauthorized

  on main.tf line 16, in resource "azuredevops_variable_group" "variablegroup":
  16: resource "azuredevops_variable_group" "variablegroup" {

**Comment by xuzhang3** [comment]
Hi @GeromeRen ,   If you just want manage variable groups. In ADO provider, you need   `build `, `variables group` permissions.
![image](https://user-images.githubusercontent.com/57888764/87112268-f5efaa00-c29d-11ea-976f-0b4dc084339c.png)
 `token`  is a kind of permission aggregation which will can provide multiple  resources permissions.

**Comment by xuzhang3** [comment]
Closing this issue. Feel free to reopen it if you still have questions.

**Comment by aleqsss** [comment]
Hello,

@xuzhang3

If there's additional scopes needed, other than: 

- **Variable Groups:** Read, Create, & Manage

Such as (discussed above in this thread):

- **Build:** Read & execute
**AND/OR**
- **Tokens:** Read & manage

I'd like to propose that those scopes should be added to the [PAT Permissions Required section](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/variable_group#pat-permissions-required)  of the Terraform azuredevops provider (azuredevops_variable_group) documentation.

Or is there a reason as of why it only lists _**Variable Groups:** Read, Create, & Manage_ as required permissions? 🙂

This because I also struggled with various **401 Unauthorized** messages in my Terraform configuration, which manages variable groups via this provider. It could have saved me, and possibly others some troubleshooting time.

**Comment by xuzhang3** [comment]
@aleqsss  ADO is provide the ability to mange project level resources, ADO won't only one APIs when  you try create/update resources.  `variable group`  will check if you have grant the permission to the pipelines ,this is why ADO need  `Build` permissions. Thank for your update, the `variable group` doc is out of update and we need update it.

**Comment by aleqsss** [comment]
Thank you for the information @xuzhang3. 

For your information - adding the build scope permissions solved the problem for me.
