### ISSUE TITLE
azuredevops_project_features only works with a 'full-access' PAT

### ISSUE THREAD

**Issue by okamilobo** [microsoft/terraform-provider-azuredevops#712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/microsoft/azuredevops v0.3.0

### Affected Resource(s)

azuredevops_project_features

### Terraform Configuration Files

resource azuredevops_project this {
  name        = var.project_name
}

resource "azuredevops_project_features" "this" {
  project_id = azuredevops_project.this.id
  features = {
    "artifacts"     = var.artifacts_feature
    "boards"        = var.boards_feature
    "pipelines"     = var.pipeline_feature
    "testplans"     = var.testplans_feature
    "repositories"  = var.repositories_feature
  }
}

### Debug Output
N/A

### Panic Output

N/A

### Expected Behavior

According to https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/project_features I should be able to provide a PAT with the Permissions Required of: Project & Team: Read, Write, & Manage. 

### Actual Behavior

Get 401 Unauthorized response for both creating or for existing and refreshing state.  Example: 
Error:  Get project features error, project: 2218df7a-5cf4-41a1-aec3-50951e739e0d, error: Request returned status: 401 Unauthorized

Only PATs with 'Full Access' can exercise this resource.

### Steps to Reproduce

1. Setup a service account as user in your ADO org.  
2. Add the service account to the Organization level Project Collection Administrators group.
3. Create a PAT as 'Custom Defined' with the needed permissions such as Project & Team: Read, Write, & Manage
4. Init and Apply the terraform.
5. azuredevops_project resource is created but receive a 401 Unauthorized error message for the azuredevops_project_features resource.  (Note, the service account is added a project admin automatically.)
6. Change the PAT to 'Full Access'.
7. Do a TF apply, and the features resource is created.
8. Change the PAT to 'Custom Defined.'
9. Expand all of the scopes and set them to maximum levels of access.
10. Do a TF apply; the refresh fails with a 401 Unauthorized error.  

### Important Factoids

N/A

### References

https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/project_features

* #0000

**Comment by xuzhang3** [comment]
This is a know issue. Service team used to confirm that  some of the features can only be managed by full-access PAT.

**Comment by rob-zz** [comment]
Unfortunately, yes. See also #625 .

**Comment by okamilobo** [comment]
> Unfortunately, yes. See also #625 .

I looked for any previously reported issue and didn't find this...  Perhaps the documentation can be updated so there is less confusion and troubleshooting by your consumers?  

Is this a bug introduced with the 6.x APIs or was this is a conscious decision on someone's part?

**Comment by xuzhang3** [comment]
@okamilobo There used to be a notification in [Restrict creation of full-scoped PATs](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/manage-pats-with-policies-for-administrators?view=azure-devops#restrict-creation-of-full-scoped-pats) that some of the features need full-scope PAT. Since the document has been updated, the PAT issue might have been resolved. But the project feature API used here is preview APIs, which is probably why it still requires a full-scope PAT.

**Comment by okamilobo** [comment]
> But the project feature API used here is preview APIs, which is probably why it still requires a full-scope PAT.

I looked through the open and closed issues and didn't find any mention of the provider moving onto a GA version of the API.  What is the plan to move to 6.x GA (2019) or even 7.0 (2022)?

**Comment by xuzhang3** [comment]
@okamilobo  currently not ETA for v7.x SDK(https://github.com/microsoft/azure-devops-go-api/issues/123),  I was considering generate a private SDK.

**Comment by xuzhang3** [comment]
@okamilobo  Project features scope are not documented. You need mange the custom permissions by [PAT API](https://learn.microsoft.com/en-us/rest/api/azure/devops/tokens/pats/create?view=azure-devops-rest-7.0&tabs=HTTP) or C# code.  The permission scope in this issue is `vso.features` and `vso.features_write`.

**Note**:  To use the PAT API, you must authenticate with an [Azure AD token](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens). Please see [Manage personal access tokens (PATs) using REST API](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/manage-personal-access-tokens-via-api?view=azure-devops) for details.

[PAT permission scopes](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-security-configuration/configuration-guides/pat-fullscope-burndown)
